---
abstract: 'Install the Lego modules.'
author:
  - 'Michal Josef Spacek <skim@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.21'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-Lego
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Lego::From::PNG: 0.04
  Lego::Ldraw: 0.5.8
  Lego::Part: '0.03'
  Lego::Part::Image: '0.05'
  perl: 5.6.0
resources:
  bugtracker: https://github.com/michal-josef-spacek/Task-Lego/issues
  homepage: https://github.com/michal-josef-spacek/Task-Lego
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/michal-josef-spacek/Task-Lego
version: '0.05'
